module.exports = {
    sendgrid: '',
    AZURE_STORAGE_CONNECTION_STRING: '',
    TWITTER_CONSUMER_KEY: 'KMM4Y0BppwYD5KmsQiRiyiASF',
    TWITTER_CONSUMER_SECRET: 'buDXljU2TFyHXZ4GH6YiidbRlpopjs5TZNdDOpMBPFFqMaSrDI',
    TWITTER_ACCESS_TOKEN_KEY: '2943227683-5CYKacngWfFa6gBy4Kfmni5On19tach9aIJwPLw',
    TWITTER_ACCESS_TOKEN_SECRET: 'kwxhbBD4QfgZqnEC7sxfXXIEPh4dygRxBG1jFb962i0CC'
}